"""add comment table

Revision ID: 07e64bfb3773
Revises: 5860975589b9
Create Date: 2026-07-06 22:00:31.207605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e64bfb3773'
down_revision: Union[str, None] = '5860975589b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_audience'), 'comment', ['audience'], unique=False)
    op.create_index(op.f('ix_comment_company_id'), 'comment', ['company_id'], unique=False)
    op.create_index(op.f('ix_comment_organization_id'), 'comment', ['organization_id'], unique=False)
    op.create_index(op.f('ix_comment_period'), 'comment', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_period'), table_name='comment')
    op.drop_index(op.f('ix_comment_organization_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_company_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_audience'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
