"""add accuracy_report table

Revision ID: 1c0d9fa20248
Revises: c75ace7ccfae
Create Date: 2026-07-14 12:18:36.158907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c0d9fa20248'
down_revision: Union[str, None] = 'c75ace7ccfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accuracy_report',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=50), nullable=False),
    sa.Column('scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accuracy_report_company_id'), 'accuracy_report', ['company_id'], unique=False)
    op.create_index(op.f('ix_accuracy_report_document_id'), 'accuracy_report', ['document_id'], unique=False)
    op.create_index(op.f('ix_accuracy_report_organization_id'), 'accuracy_report', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accuracy_report_organization_id'), table_name='accuracy_report')
    op.drop_index(op.f('ix_accuracy_report_document_id'), table_name='accuracy_report')
    op.drop_index(op.f('ix_accuracy_report_company_id'), table_name='accuracy_report')
    op.drop_table('accuracy_report')
    # ### end Alembic commands ###
