"""add audience and period to insight

Revision ID: 4639bd4425ac
Revises: 881bb165afd0
Create Date: 2026-07-03 13:14:58.138419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4639bd4425ac'
down_revision: Union[str, None] = '881bb165afd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insight', sa.Column('audience', sa.String(length=20), nullable=False))
    op.add_column('insight', sa.Column('period_start', sa.Date(), nullable=False))
    op.add_column('insight', sa.Column('period_end', sa.Date(), nullable=False))
    op.create_index(op.f('ix_insight_audience'), 'insight', ['audience'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insight_audience'), table_name='insight')
    op.drop_column('insight', 'period_end')
    op.drop_column('insight', 'period_start')
    op.drop_column('insight', 'audience')
    # ### end Alembic commands ###
