"""add budget table

Revision ID: 5860975589b9
Revises: df2e307ce0bd
Create Date: 2026-07-06 21:23:59.558780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5860975589b9'
down_revision: Union[str, None] = 'df2e307ce0bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('taxonomy_code', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_start', 'period_end', 'taxonomy_code', name='uq_budget_company_period_taxonomy')
    )
    op.create_index(op.f('ix_budget_company_id'), 'budget', ['company_id'], unique=False)
    op.create_index(op.f('ix_budget_organization_id'), 'budget', ['organization_id'], unique=False)
    op.create_index(op.f('ix_budget_taxonomy_code'), 'budget', ['taxonomy_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_taxonomy_code'), table_name='budget')
    op.drop_index(op.f('ix_budget_organization_id'), table_name='budget')
    op.drop_index(op.f('ix_budget_company_id'), table_name='budget')
    op.drop_table('budget')
    # ### end Alembic commands ###
