"""add invitation table

Revision ID: b14a2d263449
Revises: 237e11f21cb4
Create Date: 2026-07-06 16:02:56.985184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b14a2d263449'
down_revision: Union[str, None] = '237e11f21cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column(
        'role',
        postgresql.ENUM('OWNER', 'ADMIN', 'ANALYST', 'VIEWER', name='user_role', create_type=False),
        nullable=False,
    ),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', name='invitation_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_email'), 'invitation', ['email'], unique=False)
    op.create_index(op.f('ix_invitation_organization_id'), 'invitation', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invitation_token'), 'invitation', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_token'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_organization_id'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_email'), table_name='invitation')
    op.drop_table('invitation')
    # ### end Alembic commands ###
