"""make metric value nullable and add reason

Revision ID: c90997760daf
Revises: ee532ad58083
Create Date: 2026-07-07 20:40:46.898411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90997760daf'
down_revision: Union[str, None] = 'ee532ad58083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('reason', sa.String(length=500), nullable=True))
    op.alter_column('metric', 'value',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metric', 'value',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               nullable=False)
    op.drop_column('metric', 'reason')
    # ### end Alembic commands ###
