"""add 2fa fields to user

Revision ID: df2e307ce0bd
Revises: b14a2d263449
Create Date: 2026-07-06 16:45:43.953857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df2e307ce0bd'
down_revision: Union[str, None] = 'b14a2d263449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column(
        'user', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    op.alter_column('user', 'totp_enabled', server_default=None)
    op.add_column('user', sa.Column('backup_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'backup_codes')
    op.drop_column('user', 'totp_enabled')
    op.drop_column('user', 'totp_secret')
    # ### end Alembic commands ###
