"""add auto-fetch fields to company and document

Revision ID: ea94d7d87e76
Revises: 6f5469cb3d93
Create Date: 2026-07-06 23:54:40.625280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea94d7d87e76'
down_revision: Union[str, None] = '6f5469cb3d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('investor_relations_url', sa.String(length=2000), nullable=True))
    op.add_column(
        'company',
        sa.Column('auto_fetch_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('company', sa.Column('last_fetch_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('company', sa.Column('last_fetch_result', sa.Text(), nullable=True))
    # Existing rows all came from manual upload (this feature is what introduces
    # any other source_type), so backfill them accordingly rather than leaving a
    # NOT NULL column with nothing to fill it.
    op.add_column(
        'document',
        sa.Column('source_type', sa.String(length=20), nullable=False, server_default='manual_upload'),
    )
    op.add_column('document', sa.Column('source_url', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'source_url')
    op.drop_column('document', 'source_type')
    op.drop_column('company', 'last_fetch_result')
    op.drop_column('company', 'last_fetch_checked_at')
    op.drop_column('company', 'auto_fetch_enabled')
    op.drop_column('company', 'investor_relations_url')
    # ### end Alembic commands ###
