"""add external_source_id to document

Revision ID: ee532ad58083
Revises: ea94d7d87e76
Create Date: 2026-07-07 19:12:26.399348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee532ad58083'
down_revision: Union[str, None] = 'ea94d7d87e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('external_source_id', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_document_external_source_id'), 'document', ['external_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_external_source_id'), table_name='document')
    op.drop_column('document', 'external_source_id')
    # ### end Alembic commands ###
